name: CI/CD Desafio Stefanini - Web

on:
  push:
    branches:
      - main
    paths:
      - 'src/DesafioStefanini.Web/**'

  workflow_dispatch: # Gatilho manual mantido

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    defaults:
      run:
        working-directory: ./src/DesafioStefanini.Web

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # MUDANÇA CRÍTICA: O Node 20 resolve o erro ERR_REQUIRE_ESM
          cache: 'npm'
          cache-dependency-path: './src/DesafioStefanini.Web/package-lock.json'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Create Environment File
        run: |
          mkdir -p src/environments
          cat <<EOF > src/environments/environment.prod.ts
          export const environment = {
            production: true,
            apiUrl: '${{ secrets.API_URL }}'
          };
          EOF

      - name: Build Project
        # Rodando direto o comando para evitar problemas de escopo do npx
        run: npm run build -- --configuration production --base-href /desafio-stefanini/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Ajustado para o nome do projeto que apareceu no seu log
          folder: src/DesafioStefanini.Web/dist/desafio-stefanini-web/browser
          branch: gh-pages
